### PR TITLE
Fix fortran dependency bug, fixes #35

### LINKED ISSUE #35: Fortran error with GCC-8.1.0 Rtools
The new gcc 8.1.0 Fortran compiler fails here:

https://github.com/RBigData/pbdBASE/blob/618b9299ae2ff412667f814b793e5babea540605/src/utils/subset_special.f90#L63-L65

With this error [(full build log)](https://github.com/r-windows/checks/blob/master/pbdBASE.Rcheck/00install.out):

```
Fatal Error: Can't open module file 'sorts.mod' for reading at (1): No such file or directory
compilation terminated.
```

I know very little about fortran. Is this a bug in the toolchain? We also have a new version of `make`, perhaps there is an issue with your `Makevars.win`?

### PR DESCRIPTION
**Pull request by jeroen**
See issue https://github.com/RBigData/pbdBASE/issues/35

### CODE REVIEW

**Comment by wrathematics** [comment]
Thanks!

**Comment by jeroen** [comment]
Would it be possible to try to push to CRAN? You would really help me with this :-)

**Comment by wrathematics** [comment]
Well, a certain professor yanked the package from me. When I submitted fixes they requested, the submission was rejected because examples were marked with `\dontrun{}` (they actually CAN'T run, because the package is designed for SPMD). We added a shim to spawn separate processes to satisfy their new misguided rule about running examples, but it's incomplete. I'll be honest, the fact that CRAN wasn't even willing to entertain a negotiation put it at the very bottom of my priority list.

I can try, but it'll probably take a few days to finish up the example stuff.

**Comment by jeroen** [comment]
Yes complying with CRAN demands can be painful, I know :) I think you're allowed to use `\donttest{}` instead of `\dontrun{}` ? Either way I really appreciate your effort to get this fix on CRAN :)

**Comment by wrathematics** [comment]
I have been trying to get it onto CRAN, but I keep running into issues.

**Comment by jeroen** [comment]
Still no luck? What is the reason that it gets rejected?

**Comment by wrathematics** [comment]
It's currently failing on some automated pre-check because of missing package dependencies on Debian. But noting's changed, so I think it's a system configuration issue on their side. Basically, it looks to them like the package update has new ERRORs over the old one.

The first thing they tried was to re-run the build, but same result. That was a few days ago, and I didn't respond because I wasn't sure if they monitored those emails. I just sent them another email.

**Pull request merged**
